---
title: "RECS 2009"
author: "Ravi Goparaju, Jatin Konchady, Andrew Xiao, Paul Yun"
resource_files:
- .Renviron
output:
  html_notebook:
    code_folding: hide
    toc: yes
    toc_depth: 4
    toc_float: yes
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(data.world)
library(DT)
library(plotly)
library(lubridate)
library(ggplot2)
knitr::opts_chunk$set(echo = TRUE)
```

<!--For the first input panel-->
```{r}
project <- "https://data.world/ravi-goparaju/s18-edv-project-1-dataset" 
data.world::set_config(cfg_env("DW_API")) 
regions <- data.world::query(data.world::qry_sql(
 "   
  	select * from energy 
 "), 
dataset = project)
```

##Data World stuff
<p>Our data.world project can be viewed [here](https://data.world/ravi-goparaju/residential-energy-consumption-2009) and the  insights we've made can be viewed [here](https://data.world/ravi-goparaju/residential-energy-consumption-2009/insights)</p>
<br>

```{r}
project <- "https://data.world/ravi-goparaju/s18-edv-project-1-dataset" 
data.world::set_config(cfg_env("DW_API")) 
regions <- data.world::query(data.world::qry_sql(
 "   
  	select regionc from energy 
 "), 
dataset = project)
```

```{r}
inputPanel(
  selectInput("selectRegion", label = "Select Region",choices = regions, multiple=TRUE, selected=c("Northeast", "Midwest", "South", "West"))
)


```

```{r}
df <- eventReactive(c(input$selectRegion), { 
  project <- "https://data.world/ravi-goparaju/s18-edv-project-1-dataset"  
  data.world::set_config(cfg_env("DW_API")) 
  paramQuery <- data.world::qry_sql(
   "   
    select *
    from energy s
    where regionc in (?, ?, ?, ?)
order by regionc
   ")
  paramQuery$params <- c(input$selectRegion[1], input$selectRegion[2], input$selectRegion[3], input$selectRegion[4])
  data.world::query(paramQuery, dataset = project)
}) 

```

```{r}
Regions <- eventReactive(c(input$selectRegion), { 
  library('stringr')
  str_c(input$selectRegion, collapse= ' , ')
})
```

```{r}
renderDataTable({
  DT::datatable(df(), rownames = FALSE,
  extensions = list(Responsive = TRUE, FixedHeader = FALSE)
  )
})
```
